"""add word_cefr_levels table

Revision ID: 0972185dbc56
Revises: cfd96b2873aa
Create Date: 2026-04-30 12:21:39.702329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0972185dbc56'
down_revision: Union[str, Sequence[str], None] = 'cfd96b2873aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_cefr_levels',
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_cefr_levels')
    # ### end Alembic commands ###
