"""add_calibration_tables

Revision ID: 2d5794db0de0
Revises: b2c3d4e5f6a7
Create Date: 2026-05-29 11:43:44.895096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5794db0de0'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibration_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['calibration_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_responses_item_id'), 'calibration_responses', ['item_id'], unique=False)
    op.create_index(op.f('ix_calibration_responses_user_id'), 'calibration_responses', ['user_id'], unique=False)
    op.add_column('users', sa.Column('calibration_done', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'calibration_done')
    op.drop_index(op.f('ix_calibration_responses_user_id'), table_name='calibration_responses')
    op.drop_index(op.f('ix_calibration_responses_item_id'), table_name='calibration_responses')
    op.drop_table('calibration_responses')
    op.drop_table('calibration_items')
    # ### end Alembic commands ###
