"""drop translation_cache table

Revision ID: 3eafa49c7ef2
Revises: 794448bbb016
Create Date: 2026-05-03 14:47:30.865507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3eafa49c7ef2'
down_revision: Union[str, Sequence[str], None] = '794448bbb016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_text', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('context_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('source_lang', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('target_lang', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('hit_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('translation_cache_pkey')),
    sa.UniqueConstraint('source_text', 'context_hash', 'source_lang', 'target_lang', 'provider', name=op.f('uq_translation_cache_lookup'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
