"""added reading level and use of ml to user

Revision ID: 52cfc1bf26de
Revises: 827296bd2179
Create Date: 2026-04-29 10:13:14.731195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cfc1bf26de'
down_revision: Union[str, Sequence[str], None] = '827296bd2179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reading_level', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('use_ml_predictions', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'use_ml_predictions')
    op.drop_column('users', 'reading_level')
    # ### end Alembic commands ###
