"""update translation_cache for multi-translation

Revision ID: 794448bbb016
Revises: 0972185dbc56
Create Date: 2026-04-30 14:23:05.527903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '794448bbb016'
down_revision: Union[str, Sequence[str], None] = '0972185dbc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.String(length=256), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('source_lang', sa.String(length=8), nullable=False),
    sa.Column('target_lang', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_text', 'context_hash', 'source_lang', 'target_lang', 'provider', name='uq_translation_cache_lookup')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation_cache')
    # ### end Alembic commands ###
