"""making user more basic for login

Revision ID: 827296bd2179
Revises: 9257799bca0b
Create Date: 2026-04-29 10:01:04.041308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827296bd2179'
down_revision: Union[str, Sequence[str], None] = '9257799bca0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reading_level')
    op.drop_column('users', 'difficulty_mode')
    op.drop_column('users', 'assistance_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assistance_mode', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('difficulty_mode', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('reading_level', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
