"""epub chapters and images

Revision ID: ac94ff69eba6
Revises: c8ffc9118f9b
Create Date: 2026-06-01 15:37:41.749955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac94ff69eba6'
down_revision: Union[str, Sequence[str], None] = 'c8ffc9118f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chapter_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_document_id'), 'chapters', ['document_id'], unique=False)
    op.create_table('epub_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.Column('after_paragraph_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epub_images_page_id'), 'epub_images', ['page_id'], unique=False)
    op.add_column('pages', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pages_chapter_id'), 'pages', ['chapter_id'], unique=False)
    op.create_foreign_key('fk_pages_chapter_id', 'pages', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pages_chapter_id', 'pages', type_='foreignkey')
    op.drop_index(op.f('ix_pages_chapter_id'), table_name='pages')
    op.drop_column('pages', 'chapter_id')
    op.drop_index(op.f('ix_epub_images_page_id'), table_name='epub_images')
    op.drop_table('epub_images')
    op.drop_index(op.f('ix_chapters_document_id'), table_name='chapters')
    op.drop_table('chapters')
    # ### end Alembic commands ###
