"""add study_level to documents

Revision ID: c0e9eeac7d91
Revises: c4e8a2f60b17
Create Date: 2026-07-17 17:48:37.822784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e9eeac7d91'
down_revision: Union[str, Sequence[str], None] = 'c4e8a2f60b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('study_level', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'study_level')
    # ### end Alembic commands ###
