"""highlighted_words replace was_clicked with clicked_word_id fk

Revision ID: d356ae19fb20
Revises: d6bb00f16033
Create Date: 2026-05-19 14:07:29.296091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd356ae19fb20'
down_revision: Union[str, Sequence[str], None] = 'd6bb00f16033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlighted_words', sa.Column('clicked_word_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'highlighted_words', 'clicked_words', ['clicked_word_id'], ['id'], ondelete='SET NULL')
    op.drop_column('highlighted_words', 'was_clicked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlighted_words', sa.Column('was_clicked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'highlighted_words', type_='foreignkey')
    op.drop_column('highlighted_words', 'clicked_word_id')
    # ### end Alembic commands ###
