"""add highlighted_words table

Revision ID: d6bb00f16033
Revises: c37ed3f0ce82
Create Date: 2026-05-19 13:51:11.085635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6bb00f16033'
down_revision: Union[str, Sequence[str], None] = 'c37ed3f0ce82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlighted_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('was_clicked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', 'page_number', 'word', name='uq_highlighted_user_doc_page_word')
    )
    op.create_index(op.f('ix_highlighted_words_document_id'), 'highlighted_words', ['document_id'], unique=False)
    op.create_index(op.f('ix_highlighted_words_user_id'), 'highlighted_words', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_highlighted_words_user_id'), table_name='highlighted_words')
    op.drop_index(op.f('ix_highlighted_words_document_id'), table_name='highlighted_words')
    op.drop_table('highlighted_words')
    # ### end Alembic commands ###
